# This file was automatically generated by SWIG (http://www.swig.org).
# Version 4.0.1
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.

from sys import version_info as _swig_python_version_info
if _swig_python_version_info < (2, 7, 0):
    raise RuntimeError("Python 2.7 or later required")

# Import the low-level C/C++ module
if __package__ or "." in __name__:
    from . import _lib
else:
    import _lib

try:
    import builtins as __builtin__
except ImportError:
    import __builtin__

def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)


def _swig_setattr_nondynamic_instance_variable(set):
    def set_instance_attr(self, name, value):
        if name == "thisown":
            self.this.own(value)
        elif name == "this":
            set(self, name, value)
        elif hasattr(self, name) and isinstance(getattr(type(self), name), property):
            set(self, name, value)
        else:
            raise AttributeError("You cannot add instance attributes to %s" % self)
    return set_instance_attr


def _swig_setattr_nondynamic_class_variable(set):
    def set_class_attr(cls, name, value):
        if hasattr(cls, name) and not isinstance(getattr(cls, name), property):
            set(cls, name, value)
        else:
            raise AttributeError("You cannot add class attributes to %s" % cls)
    return set_class_attr


def _swig_add_metaclass(metaclass):
    """Class decorator for adding a metaclass to a SWIG wrapped class - a slimmed down version of six.add_metaclass"""
    def wrapper(cls):
        return metaclass(cls.__name__, cls.__bases__, cls.__dict__.copy())
    return wrapper


class _SwigNonDynamicMeta(type):
    """Meta class to enforce nondynamic attributes (no new attributes) for a class"""
    __setattr__ = _swig_setattr_nondynamic_class_variable(type.__setattr__)


class SwigPyIterator(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_destroy__ = _lib.delete_SwigPyIterator

    def value(self):
        return _lib.SwigPyIterator_value(self)

    def incr(self, n=1):
        return _lib.SwigPyIterator_incr(self, n)

    def decr(self, n=1):
        return _lib.SwigPyIterator_decr(self, n)

    def distance(self, x):
        return _lib.SwigPyIterator_distance(self, x)

    def equal(self, x):
        return _lib.SwigPyIterator_equal(self, x)

    def copy(self):
        return _lib.SwigPyIterator_copy(self)

    def next(self):
        return _lib.SwigPyIterator_next(self)

    def __next__(self):
        return _lib.SwigPyIterator___next__(self)

    def previous(self):
        return _lib.SwigPyIterator_previous(self)

    def advance(self, n):
        return _lib.SwigPyIterator_advance(self, n)

    def __eq__(self, x):
        return _lib.SwigPyIterator___eq__(self, x)

    def __ne__(self, x):
        return _lib.SwigPyIterator___ne__(self, x)

    def __iadd__(self, n):
        return _lib.SwigPyIterator___iadd__(self, n)

    def __isub__(self, n):
        return _lib.SwigPyIterator___isub__(self, n)

    def __add__(self, n):
        return _lib.SwigPyIterator___add__(self, n)

    def __sub__(self, *args):
        return _lib.SwigPyIterator___sub__(self, *args)
    def __iter__(self):
        return self

# Register SwigPyIterator in _lib:
_lib.SwigPyIterator_swigregister(SwigPyIterator)

class IntVector(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def iterator(self):
        return _lib.IntVector_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _lib.IntVector___nonzero__(self)

    def __bool__(self):
        return _lib.IntVector___bool__(self)

    def __len__(self):
        return _lib.IntVector___len__(self)

    def __getslice__(self, i, j):
        return _lib.IntVector___getslice__(self, i, j)

    def __setslice__(self, *args):
        return _lib.IntVector___setslice__(self, *args)

    def __delslice__(self, i, j):
        return _lib.IntVector___delslice__(self, i, j)

    def __delitem__(self, *args):
        return _lib.IntVector___delitem__(self, *args)

    def __getitem__(self, *args):
        return _lib.IntVector___getitem__(self, *args)

    def __setitem__(self, *args):
        return _lib.IntVector___setitem__(self, *args)

    def pop(self):
        return _lib.IntVector_pop(self)

    def append(self, x):
        return _lib.IntVector_append(self, x)

    def empty(self):
        return _lib.IntVector_empty(self)

    def size(self):
        return _lib.IntVector_size(self)

    def swap(self, v):
        return _lib.IntVector_swap(self, v)

    def begin(self):
        return _lib.IntVector_begin(self)

    def end(self):
        return _lib.IntVector_end(self)

    def rbegin(self):
        return _lib.IntVector_rbegin(self)

    def rend(self):
        return _lib.IntVector_rend(self)

    def clear(self):
        return _lib.IntVector_clear(self)

    def get_allocator(self):
        return _lib.IntVector_get_allocator(self)

    def pop_back(self):
        return _lib.IntVector_pop_back(self)

    def erase(self, *args):
        return _lib.IntVector_erase(self, *args)

    def __init__(self, *args):
        _lib.IntVector_swiginit(self, _lib.new_IntVector(*args))

    def push_back(self, x):
        return _lib.IntVector_push_back(self, x)

    def front(self):
        return _lib.IntVector_front(self)

    def back(self):
        return _lib.IntVector_back(self)

    def assign(self, n, x):
        return _lib.IntVector_assign(self, n, x)

    def resize(self, *args):
        return _lib.IntVector_resize(self, *args)

    def insert(self, *args):
        return _lib.IntVector_insert(self, *args)

    def reserve(self, n):
        return _lib.IntVector_reserve(self, n)

    def capacity(self):
        return _lib.IntVector_capacity(self)
    __swig_destroy__ = _lib.delete_IntVector

# Register IntVector in _lib:
_lib.IntVector_swigregister(IntVector)

class DoubleVector(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def iterator(self):
        return _lib.DoubleVector_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _lib.DoubleVector___nonzero__(self)

    def __bool__(self):
        return _lib.DoubleVector___bool__(self)

    def __len__(self):
        return _lib.DoubleVector___len__(self)

    def __getslice__(self, i, j):
        return _lib.DoubleVector___getslice__(self, i, j)

    def __setslice__(self, *args):
        return _lib.DoubleVector___setslice__(self, *args)

    def __delslice__(self, i, j):
        return _lib.DoubleVector___delslice__(self, i, j)

    def __delitem__(self, *args):
        return _lib.DoubleVector___delitem__(self, *args)

    def __getitem__(self, *args):
        return _lib.DoubleVector___getitem__(self, *args)

    def __setitem__(self, *args):
        return _lib.DoubleVector___setitem__(self, *args)

    def pop(self):
        return _lib.DoubleVector_pop(self)

    def append(self, x):
        return _lib.DoubleVector_append(self, x)

    def empty(self):
        return _lib.DoubleVector_empty(self)

    def size(self):
        return _lib.DoubleVector_size(self)

    def swap(self, v):
        return _lib.DoubleVector_swap(self, v)

    def begin(self):
        return _lib.DoubleVector_begin(self)

    def end(self):
        return _lib.DoubleVector_end(self)

    def rbegin(self):
        return _lib.DoubleVector_rbegin(self)

    def rend(self):
        return _lib.DoubleVector_rend(self)

    def clear(self):
        return _lib.DoubleVector_clear(self)

    def get_allocator(self):
        return _lib.DoubleVector_get_allocator(self)

    def pop_back(self):
        return _lib.DoubleVector_pop_back(self)

    def erase(self, *args):
        return _lib.DoubleVector_erase(self, *args)

    def __init__(self, *args):
        _lib.DoubleVector_swiginit(self, _lib.new_DoubleVector(*args))

    def push_back(self, x):
        return _lib.DoubleVector_push_back(self, x)

    def front(self):
        return _lib.DoubleVector_front(self)

    def back(self):
        return _lib.DoubleVector_back(self)

    def assign(self, n, x):
        return _lib.DoubleVector_assign(self, n, x)

    def resize(self, *args):
        return _lib.DoubleVector_resize(self, *args)

    def insert(self, *args):
        return _lib.DoubleVector_insert(self, *args)

    def reserve(self, n):
        return _lib.DoubleVector_reserve(self, n)

    def capacity(self):
        return _lib.DoubleVector_capacity(self)
    __swig_destroy__ = _lib.delete_DoubleVector

# Register DoubleVector in _lib:
_lib.DoubleVector_swigregister(DoubleVector)

class DoubleVector2(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def iterator(self):
        return _lib.DoubleVector2_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _lib.DoubleVector2___nonzero__(self)

    def __bool__(self):
        return _lib.DoubleVector2___bool__(self)

    def __len__(self):
        return _lib.DoubleVector2___len__(self)

    def __getslice__(self, i, j):
        return _lib.DoubleVector2___getslice__(self, i, j)

    def __setslice__(self, *args):
        return _lib.DoubleVector2___setslice__(self, *args)

    def __delslice__(self, i, j):
        return _lib.DoubleVector2___delslice__(self, i, j)

    def __delitem__(self, *args):
        return _lib.DoubleVector2___delitem__(self, *args)

    def __getitem__(self, *args):
        return _lib.DoubleVector2___getitem__(self, *args)

    def __setitem__(self, *args):
        return _lib.DoubleVector2___setitem__(self, *args)

    def pop(self):
        return _lib.DoubleVector2_pop(self)

    def append(self, x):
        return _lib.DoubleVector2_append(self, x)

    def empty(self):
        return _lib.DoubleVector2_empty(self)

    def size(self):
        return _lib.DoubleVector2_size(self)

    def swap(self, v):
        return _lib.DoubleVector2_swap(self, v)

    def begin(self):
        return _lib.DoubleVector2_begin(self)

    def end(self):
        return _lib.DoubleVector2_end(self)

    def rbegin(self):
        return _lib.DoubleVector2_rbegin(self)

    def rend(self):
        return _lib.DoubleVector2_rend(self)

    def clear(self):
        return _lib.DoubleVector2_clear(self)

    def get_allocator(self):
        return _lib.DoubleVector2_get_allocator(self)

    def pop_back(self):
        return _lib.DoubleVector2_pop_back(self)

    def erase(self, *args):
        return _lib.DoubleVector2_erase(self, *args)

    def __init__(self, *args):
        _lib.DoubleVector2_swiginit(self, _lib.new_DoubleVector2(*args))

    def push_back(self, x):
        return _lib.DoubleVector2_push_back(self, x)

    def front(self):
        return _lib.DoubleVector2_front(self)

    def back(self):
        return _lib.DoubleVector2_back(self)

    def assign(self, n, x):
        return _lib.DoubleVector2_assign(self, n, x)

    def resize(self, *args):
        return _lib.DoubleVector2_resize(self, *args)

    def insert(self, *args):
        return _lib.DoubleVector2_insert(self, *args)

    def reserve(self, n):
        return _lib.DoubleVector2_reserve(self, n)

    def capacity(self):
        return _lib.DoubleVector2_capacity(self)
    __swig_destroy__ = _lib.delete_DoubleVector2

# Register DoubleVector2 in _lib:
_lib.DoubleVector2_swigregister(DoubleVector2)

class DDE(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    y = property(_lib.DDE_y_get, _lib.DDE_y_set)
    yp = property(_lib.DDE_yp_get, _lib.DDE_yp_set)
    t_ar = property(_lib.DDE_t_ar_get, _lib.DDE_t_ar_set)
    t_simulation = property(_lib.DDE_t_simulation_get, _lib.DDE_t_simulation_set)
    num_iteration = property(_lib.DDE_num_iteration_get, _lib.DDE_num_iteration_set)
    __swig_destroy__ = _lib.delete_DDE

    def set_params(self, t_simulation, dt, I_C, I_Str, wSG, wGS, wCS, wSC, wGG, wCC):
        return _lib.DDE_set_params(self, t_simulation, dt, I_C, I_Str, wSG, wGS, wCS, wSC, wGG, wCC)

    def set_history(self, hist):
        return _lib.DDE_set_history(self, hist)

    def euler_integrator(self):
        return _lib.DDE_euler_integrator(self)

    def FS(self, x):
        return _lib.DDE_FS(self, x)

    def FG(self, x):
        return _lib.DDE_FG(self, x)

    def FE(self, x):
        return _lib.DDE_FE(self, x)

    def FI(self, x):
        return _lib.DDE_FI(self, x)

    def sys_eqs(self, dxdt, t, n, plag):
        return _lib.DDE_sys_eqs(self, dxdt, t, n, plag)

    def interp_x(self, t, i, n0):
        return _lib.DDE_interp_x(self, t, i, n0)

    def __init__(self):
        _lib.DDE_swiginit(self, _lib.new_DDE())

# Register DDE in _lib:
_lib.DDE_swigregister(DDE)


def lerp(v0, v1, t):
    return _lib.lerp(v0, v1, t)


