# This file was automatically generated by SWIG (http://www.swig.org).
# Version 3.0.12
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.

from sys import version_info as _swig_python_version_info
if _swig_python_version_info >= (2, 7, 0):
    def swig_import_helper():
        import importlib
        pkg = __name__.rpartition('.')[0]
        mname = '.'.join((pkg, '_lib')).lstrip('.')
        try:
            return importlib.import_module(mname)
        except ImportError:
            return importlib.import_module('_lib')
    _lib = swig_import_helper()
    del swig_import_helper
elif _swig_python_version_info >= (2, 6, 0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_lib', [dirname(__file__)])
        except ImportError:
            import _lib
            return _lib
        try:
            _mod = imp.load_module('_lib', fp, pathname, description)
        finally:
            if fp is not None:
                fp.close()
        return _mod
    _lib = swig_import_helper()
    del swig_import_helper
else:
    import _lib
del _swig_python_version_info

try:
    _swig_property = property
except NameError:
    pass  # Python < 2.2 doesn't have 'property'.

try:
    import builtins as __builtin__
except ImportError:
    import __builtin__

def _swig_setattr_nondynamic(self, class_type, name, value, static=1):
    if (name == "thisown"):
        return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name, None)
    if method:
        return method(self, value)
    if (not static):
        if _newclass:
            object.__setattr__(self, name, value)
        else:
            self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)


def _swig_setattr(self, class_type, name, value):
    return _swig_setattr_nondynamic(self, class_type, name, value, 0)


def _swig_getattr(self, class_type, name):
    if (name == "thisown"):
        return self.this.own()
    method = class_type.__swig_getmethods__.get(name, None)
    if method:
        return method(self)
    raise AttributeError("'%s' object has no attribute '%s'" % (class_type.__name__, name))


def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except __builtin__.Exception:
    class _object:
        pass
    _newclass = 0

class SwigPyIterator(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, SwigPyIterator, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, SwigPyIterator, name)

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_destroy__ = _lib.delete_SwigPyIterator
    __del__ = lambda self: None

    def value(self):
        return _lib.SwigPyIterator_value(self)

    def incr(self, n=1):
        return _lib.SwigPyIterator_incr(self, n)

    def decr(self, n=1):
        return _lib.SwigPyIterator_decr(self, n)

    def distance(self, x):
        return _lib.SwigPyIterator_distance(self, x)

    def equal(self, x):
        return _lib.SwigPyIterator_equal(self, x)

    def copy(self):
        return _lib.SwigPyIterator_copy(self)

    def next(self):
        return _lib.SwigPyIterator_next(self)

    def __next__(self):
        return _lib.SwigPyIterator___next__(self)

    def previous(self):
        return _lib.SwigPyIterator_previous(self)

    def advance(self, n):
        return _lib.SwigPyIterator_advance(self, n)

    def __eq__(self, x):
        return _lib.SwigPyIterator___eq__(self, x)

    def __ne__(self, x):
        return _lib.SwigPyIterator___ne__(self, x)

    def __iadd__(self, n):
        return _lib.SwigPyIterator___iadd__(self, n)

    def __isub__(self, n):
        return _lib.SwigPyIterator___isub__(self, n)

    def __add__(self, n):
        return _lib.SwigPyIterator___add__(self, n)

    def __sub__(self, *args):
        return _lib.SwigPyIterator___sub__(self, *args)
    def __iter__(self):
        return self
SwigPyIterator_swigregister = _lib.SwigPyIterator_swigregister
SwigPyIterator_swigregister(SwigPyIterator)

class IntVector(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, IntVector, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, IntVector, name)
    __repr__ = _swig_repr

    def iterator(self):
        return _lib.IntVector_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _lib.IntVector___nonzero__(self)

    def __bool__(self):
        return _lib.IntVector___bool__(self)

    def __len__(self):
        return _lib.IntVector___len__(self)

    def __getslice__(self, i, j):
        return _lib.IntVector___getslice__(self, i, j)

    def __setslice__(self, *args):
        return _lib.IntVector___setslice__(self, *args)

    def __delslice__(self, i, j):
        return _lib.IntVector___delslice__(self, i, j)

    def __delitem__(self, *args):
        return _lib.IntVector___delitem__(self, *args)

    def __getitem__(self, *args):
        return _lib.IntVector___getitem__(self, *args)

    def __setitem__(self, *args):
        return _lib.IntVector___setitem__(self, *args)

    def pop(self):
        return _lib.IntVector_pop(self)

    def append(self, x):
        return _lib.IntVector_append(self, x)

    def empty(self):
        return _lib.IntVector_empty(self)

    def size(self):
        return _lib.IntVector_size(self)

    def swap(self, v):
        return _lib.IntVector_swap(self, v)

    def begin(self):
        return _lib.IntVector_begin(self)

    def end(self):
        return _lib.IntVector_end(self)

    def rbegin(self):
        return _lib.IntVector_rbegin(self)

    def rend(self):
        return _lib.IntVector_rend(self)

    def clear(self):
        return _lib.IntVector_clear(self)

    def get_allocator(self):
        return _lib.IntVector_get_allocator(self)

    def pop_back(self):
        return _lib.IntVector_pop_back(self)

    def erase(self, *args):
        return _lib.IntVector_erase(self, *args)

    def __init__(self, *args):
        this = _lib.new_IntVector(*args)
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this

    def push_back(self, x):
        return _lib.IntVector_push_back(self, x)

    def front(self):
        return _lib.IntVector_front(self)

    def back(self):
        return _lib.IntVector_back(self)

    def assign(self, n, x):
        return _lib.IntVector_assign(self, n, x)

    def resize(self, *args):
        return _lib.IntVector_resize(self, *args)

    def insert(self, *args):
        return _lib.IntVector_insert(self, *args)

    def reserve(self, n):
        return _lib.IntVector_reserve(self, n)

    def capacity(self):
        return _lib.IntVector_capacity(self)
    __swig_destroy__ = _lib.delete_IntVector
    __del__ = lambda self: None
IntVector_swigregister = _lib.IntVector_swigregister
IntVector_swigregister(IntVector)

class DoubleVector(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, DoubleVector, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, DoubleVector, name)
    __repr__ = _swig_repr

    def iterator(self):
        return _lib.DoubleVector_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _lib.DoubleVector___nonzero__(self)

    def __bool__(self):
        return _lib.DoubleVector___bool__(self)

    def __len__(self):
        return _lib.DoubleVector___len__(self)

    def __getslice__(self, i, j):
        return _lib.DoubleVector___getslice__(self, i, j)

    def __setslice__(self, *args):
        return _lib.DoubleVector___setslice__(self, *args)

    def __delslice__(self, i, j):
        return _lib.DoubleVector___delslice__(self, i, j)

    def __delitem__(self, *args):
        return _lib.DoubleVector___delitem__(self, *args)

    def __getitem__(self, *args):
        return _lib.DoubleVector___getitem__(self, *args)

    def __setitem__(self, *args):
        return _lib.DoubleVector___setitem__(self, *args)

    def pop(self):
        return _lib.DoubleVector_pop(self)

    def append(self, x):
        return _lib.DoubleVector_append(self, x)

    def empty(self):
        return _lib.DoubleVector_empty(self)

    def size(self):
        return _lib.DoubleVector_size(self)

    def swap(self, v):
        return _lib.DoubleVector_swap(self, v)

    def begin(self):
        return _lib.DoubleVector_begin(self)

    def end(self):
        return _lib.DoubleVector_end(self)

    def rbegin(self):
        return _lib.DoubleVector_rbegin(self)

    def rend(self):
        return _lib.DoubleVector_rend(self)

    def clear(self):
        return _lib.DoubleVector_clear(self)

    def get_allocator(self):
        return _lib.DoubleVector_get_allocator(self)

    def pop_back(self):
        return _lib.DoubleVector_pop_back(self)

    def erase(self, *args):
        return _lib.DoubleVector_erase(self, *args)

    def __init__(self, *args):
        this = _lib.new_DoubleVector(*args)
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this

    def push_back(self, x):
        return _lib.DoubleVector_push_back(self, x)

    def front(self):
        return _lib.DoubleVector_front(self)

    def back(self):
        return _lib.DoubleVector_back(self)

    def assign(self, n, x):
        return _lib.DoubleVector_assign(self, n, x)

    def resize(self, *args):
        return _lib.DoubleVector_resize(self, *args)

    def insert(self, *args):
        return _lib.DoubleVector_insert(self, *args)

    def reserve(self, n):
        return _lib.DoubleVector_reserve(self, n)

    def capacity(self):
        return _lib.DoubleVector_capacity(self)
    __swig_destroy__ = _lib.delete_DoubleVector
    __del__ = lambda self: None
DoubleVector_swigregister = _lib.DoubleVector_swigregister
DoubleVector_swigregister(DoubleVector)

class DoubleVector2(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, DoubleVector2, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, DoubleVector2, name)
    __repr__ = _swig_repr

    def iterator(self):
        return _lib.DoubleVector2_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _lib.DoubleVector2___nonzero__(self)

    def __bool__(self):
        return _lib.DoubleVector2___bool__(self)

    def __len__(self):
        return _lib.DoubleVector2___len__(self)

    def __getslice__(self, i, j):
        return _lib.DoubleVector2___getslice__(self, i, j)

    def __setslice__(self, *args):
        return _lib.DoubleVector2___setslice__(self, *args)

    def __delslice__(self, i, j):
        return _lib.DoubleVector2___delslice__(self, i, j)

    def __delitem__(self, *args):
        return _lib.DoubleVector2___delitem__(self, *args)

    def __getitem__(self, *args):
        return _lib.DoubleVector2___getitem__(self, *args)

    def __setitem__(self, *args):
        return _lib.DoubleVector2___setitem__(self, *args)

    def pop(self):
        return _lib.DoubleVector2_pop(self)

    def append(self, x):
        return _lib.DoubleVector2_append(self, x)

    def empty(self):
        return _lib.DoubleVector2_empty(self)

    def size(self):
        return _lib.DoubleVector2_size(self)

    def swap(self, v):
        return _lib.DoubleVector2_swap(self, v)

    def begin(self):
        return _lib.DoubleVector2_begin(self)

    def end(self):
        return _lib.DoubleVector2_end(self)

    def rbegin(self):
        return _lib.DoubleVector2_rbegin(self)

    def rend(self):
        return _lib.DoubleVector2_rend(self)

    def clear(self):
        return _lib.DoubleVector2_clear(self)

    def get_allocator(self):
        return _lib.DoubleVector2_get_allocator(self)

    def pop_back(self):
        return _lib.DoubleVector2_pop_back(self)

    def erase(self, *args):
        return _lib.DoubleVector2_erase(self, *args)

    def __init__(self, *args):
        this = _lib.new_DoubleVector2(*args)
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this

    def push_back(self, x):
        return _lib.DoubleVector2_push_back(self, x)

    def front(self):
        return _lib.DoubleVector2_front(self)

    def back(self):
        return _lib.DoubleVector2_back(self)

    def assign(self, n, x):
        return _lib.DoubleVector2_assign(self, n, x)

    def resize(self, *args):
        return _lib.DoubleVector2_resize(self, *args)

    def insert(self, *args):
        return _lib.DoubleVector2_insert(self, *args)

    def reserve(self, n):
        return _lib.DoubleVector2_reserve(self, n)

    def capacity(self):
        return _lib.DoubleVector2_capacity(self)
    __swig_destroy__ = _lib.delete_DoubleVector2
    __del__ = lambda self: None
DoubleVector2_swigregister = _lib.DoubleVector2_swigregister
DoubleVector2_swigregister(DoubleVector2)

class DDE(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, DDE, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, DDE, name)
    __repr__ = _swig_repr
    __swig_setmethods__["y"] = _lib.DDE_y_set
    __swig_getmethods__["y"] = _lib.DDE_y_get
    if _newclass:
        y = _swig_property(_lib.DDE_y_get, _lib.DDE_y_set)
    __swig_setmethods__["yp"] = _lib.DDE_yp_set
    __swig_getmethods__["yp"] = _lib.DDE_yp_get
    if _newclass:
        yp = _swig_property(_lib.DDE_yp_get, _lib.DDE_yp_set)
    __swig_setmethods__["t_ar"] = _lib.DDE_t_ar_set
    __swig_getmethods__["t_ar"] = _lib.DDE_t_ar_get
    if _newclass:
        t_ar = _swig_property(_lib.DDE_t_ar_get, _lib.DDE_t_ar_set)
    __swig_setmethods__["t_simulation"] = _lib.DDE_t_simulation_set
    __swig_getmethods__["t_simulation"] = _lib.DDE_t_simulation_get
    if _newclass:
        t_simulation = _swig_property(_lib.DDE_t_simulation_get, _lib.DDE_t_simulation_set)
    __swig_setmethods__["num_iteration"] = _lib.DDE_num_iteration_set
    __swig_getmethods__["num_iteration"] = _lib.DDE_num_iteration_get
    if _newclass:
        num_iteration = _swig_property(_lib.DDE_num_iteration_get, _lib.DDE_num_iteration_set)
    __swig_destroy__ = _lib.delete_DDE
    __del__ = lambda self: None

    def set_params(self, t_simulation, dt, I_C, I_Str, wSG, wGS, wCS, wSC, wGG, wCC):
        return _lib.DDE_set_params(self, t_simulation, dt, I_C, I_Str, wSG, wGS, wCS, wSC, wGG, wCC)

    def set_history(self, hist):
        return _lib.DDE_set_history(self, hist)

    def euler_integrator(self):
        return _lib.DDE_euler_integrator(self)

    def FS(self, x):
        return _lib.DDE_FS(self, x)

    def FG(self, x):
        return _lib.DDE_FG(self, x)

    def FE(self, x):
        return _lib.DDE_FE(self, x)

    def FI(self, x):
        return _lib.DDE_FI(self, x)

    def sys_eqs(self, dxdt, t, n, plag):
        return _lib.DDE_sys_eqs(self, dxdt, t, n, plag)

    def interp_x(self, t, i, n0):
        return _lib.DDE_interp_x(self, t, i, n0)

    def hermite_x(self, t, tn, Xn, Vn, tnp1, Xnp1, Vnp1):
        return _lib.DDE_hermite_x(self, t, tn, Xn, Vn, tnp1, Xnp1, Vnp1)

    def __init__(self):
        this = _lib.new_DDE()
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this
DDE_swigregister = _lib.DDE_swigregister
DDE_swigregister(DDE)

# This file is compatible with both classic and new-style classes.


